<?php
/*
$Id: affiliate_info.php 3 2006-05-27 04:59:07Z user $

  osCMax Power E-Commerce
  http://oscdox.com

  Copyright 2006 osCMax2005 osCMax, 2002 osCommerce

  Released under the GNU General Public License
*/

define('HEADING_TITLE', 'AABox.com Affiliate Program');
define('NAVBAR_TITLE', 'Gain extra revenue by referring new customers to AABox.com');
define('TEXT_MAIN', '<tr class=main><td>
            <br>
            Our affiliate program is a great way to earn money by referring clients and customers to our quality web hosting services. Joining is absolutely free, and activation is immediate.
            <p class=\'gtext\'><strong>Key Features</strong></p>
                                            <p><img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Earn <strong>20%</strong>  on every direct sale of web hosting services you generate.**<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Earn <strong>5%</strong>  on every sale web hosting services generated by your Sub Affilates<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Complete web stats/online tracking of Raw and Unique Clicks and commissions<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Full online view of your complete downline, so you can see who is generating referrals<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Online account management<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Low payout threshold - Checks sent out when you reach $50.00<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Link to any page on our site - Directly to any product<br>
                                            </p>
                                            <p class=\'gtext\'><strong>Stats Features</strong></p>
                                            <p><img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> View stats from any month or year, current or historical<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Stats are presented in both text AND graphical format<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Affiliates can view their downline of referred affiliates<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Money due and money paid are shown for each month<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Top 100 ranking of referring urls<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Modify your account info or delete your account online<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> In-Depth Commissions Viewer to view individual commissions<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> See a count of total hits, unique (IP address) hits, and sales<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Stats pages are &quot;live&quot; with current referral and payout data<br>
                                            </p>
                                            <p class=\'gtext\'><strong>Payouts</strong></p>
                                            <p><img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Payout is monthly, sent out by the 15th of every month when you reach the $50.00 threshold. There is a 30 day hold on all commissions.<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Any commissions not paid out are rolled over until you reach the $50.00 payout threshold.<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> There is no maximum. You will be paid commissions on what you and your downline earn. The more you refer, the more you make.<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Commissions are recurring for the life of the referral, even on your downline!<br>
                                            <img src=\'images/ar1.gif\' width=\'7\' height=\'7\'> Passive income generated by your downline.</p>
                                            <p align=\'center\' class=\'gtext\'><strong><a href=\'https://aabox.com/cgi-bin/affiliate/signup.cgi\'>Click Here to Sign Up NOW!</a></strong></p>
                                            <p align=\'center\'><font size=\'-2\'>** Dedicated servers not eligible for affiliate program sales/commissions</font></p>
</td>
</tr>');
define('TEXT_BACK', 'back');
?>